### ISSUE TITLE
Xml files have unreadable colors for '<' characters and use black over gray for attribute names

### ISSUE THREAD

**Issue by Claye-L** [jflepp/JFlepp.VS.Theme.DarkYellow#1]
![image](https://user-images.githubusercontent.com/43422061/68487258-0cdb8980-0243-11ea-8924-e65fa62d97cd.png)

Vs 2019 Community (16.3.5)

**Comment by fl3pp** [comment]
Hi @Claye-L,

Thank you for reporting your issue.

XML Files are supposed to look like this: 
![image](https://user-images.githubusercontent.com/20628550/68497015-e2de9300-0253-11ea-875a-e838fd37dbc8.png)

I think support for XML was added in version 1.4, can you verify that you are using version 1.6 of the theme?

Which filetype are you looking at, is it plain XML or some specialized format?

Edit: Are you maybe using some extension that uses system colors to paint XML files?

**Comment by Claye-L** [comment]
So i've done some experiments, all xml files have the proper scheme (like your screenshot), except files that were auto-generated by the Xamarin forms template, even though thos files are still plain .xml files.
The coloring scheme works properly for newly created .xml in a xamarin project, but not for the default generated ones. I'm guessing this is a bug of visual studio and not your extension, though i can't find any references on it.

**Comment by fl3pp** [comment]
You can file an issue at the Xamarin extension if you want, but I don't think I can help you here so I'm closing this issue now.

Thanks for reporting anyway!

**Comment by fl3pp** [comment]
Hi @Claye-L,

In the meantime, another user had a bad experience with Xamarin files (#3). The recently released version 1.12 is supposed to take care of this exact issue, as I've probably been wrong with my earlier evaluation.

I'd be pleased if you gave the extension another shot and reported back here if your issue has been solved too.

**Comment by Claye-L** [comment]
hey, yes i've updated to version 1.12 and the xamarin xml files now have a proper color scheme. I'd been using the extension since, just switching back to vscode when i needed to edit axml files. Thanks for fixing it :)

**Comment by fl3pp** [comment]
Glad to hear your problem got fixed too. Sorry for the very long delay.
