### ISSUE TITLE
Hard to read XML file

### ISSUE THREAD

**Issue by BenGeba** [jflepp/JFlepp.VS.Theme.DarkYellow#3]
Hi,
I have created a Xamarins.Forms app in Visual Studio 2019. Here I have the problem that the XML file is really hard to read. Maybe I have a wrong setting here somewhere? 

If I create another XML file and just open it, the XML is readable and the tags are white. So far I only noticed this problem with Xamarins.Forms.
![hardtoread](https://user-images.githubusercontent.com/15016481/84114318-74052a80-aa2c-11ea-853a-6e478a07b794.png)

**Comment by BenGeba** [comment]
I have seen that the closed issue already handles the same bug. There will probably be no solution yet?

**Comment by fl3pp** [comment]
Hi @Hadda90,

Thanks for submitting your issue.

I suspect Xamarin is handling it's XML files in a different way VS does "normal" XML files.

Could you do me a favor and check if you can find the "Xamarin-XML" color settings in _Tools -> Options ->Environment -> Fonts and Colors_?

![image](https://user-images.githubusercontent.com/20628550/84272740-1ce77e80-ab2e-11ea-9bd5-2733e5a66905.png)

Maybe I can override the Xamarin defaults in the template.

**Comment by BenGeba** [comment]
Hi @jflepp,

I could find the settings. The settings that need to be overwritten are the AXML color settings. 

![axml](https://user-images.githubusercontent.com/15016481/84274895-b3b53a80-ab30-11ea-8097-0550f944de1c.png)

**Comment by fl3pp** [comment]
I did some updates to some XAML and AXML sections but probably didn't find all settings. How do I create such a problematic file?

Anyway, could you install [this version](https://github.com/jflepp/JFlepp.VS.Theme.DarkYellow/files/4760519/JFlepp.VS.Theme.DarkYellow.vsix.zip) and tell me if I caught all the settings?

**Comment by BenGeba** [comment]
To reproduce the error, you must create a new project in Visual Studio. There you select a _Mobile App (Xamarin.Forms)_ with the default settings. Afterwards you have a file _Tabbar.xml_ in the Android App assembly. This file is in the folder _Resources->layout_

With the new version the file looks now like this:
![newsettings](https://user-images.githubusercontent.com/15016481/84311108-07407c00-ab63-11ea-9dc7-ff38821d4036.png)

**Comment by fl3pp** [comment]
Thank you for hanging on!

I was able to produce such a "AXML" file and adjust the colors. Now it should look like this:

![image](https://user-images.githubusercontent.com/20628550/84430841-96fd2d80-ac2a-11ea-9d1f-24bd672c3f72.png)

Here is a preview version again:

[JFlepp.VS.Theme.DarkYellow.vsix.zip](https://github.com/jflepp/JFlepp.VS.Theme.DarkYellow/files/4766900/JFlepp.VS.Theme.DarkYellow.vsix.zip)

**Comment by BenGeba** [comment]
Thanks a lot.
This looks much better and I can now read again what is written there.

**Comment by fl3pp** [comment]
Thanks for submitting your issue. Updated version on marketplace with the new colorings.
