### ISSUE TITLE
Grouping color not easily visible - Tabs Left

### ISSUE THREAD

**Issue by imPatSpence** [jflepp/JFlepp.VS.Theme.DarkYellow#5]
Noticed when using the new Vertical Tabs features (Tabs set to left) that the groups names are not easily readable. 

![image](https://user-images.githubusercontent.com/5644106/102145867-4064ec00-3e25-11eb-85db-480671a4bf02.png)

**Comment by fl3pp** [comment]
Hi @imPatSpence,

Thank you for the issue. I'm going to look into it during the next days

**Comment by fl3pp** [comment]
Fixed vertical tabs coloring and updated extension to version 1.14. Please let me know this fix doesn't solve your issue.
