### ISSUE TITLE
Publish Window background is off-white; VS' default Dark is normal

### ISSUE THREAD

**Issue by asyagelski** [jflepp/JFlepp.VS.Theme.DarkYellow#7]
Using ``JFlepp.VS.Theme.DarkYellow``

![image](https://user-images.githubusercontent.com/8888989/121575661-9fcb3f80-c9f5-11eb-863d-d6b523a41e45.png)

Using ``Dark``

![image](https://user-images.githubusercontent.com/8888989/121575722-b2de0f80-c9f5-11eb-90ed-e447e335ab3f.png)

**Comment by fl3pp** [comment]
Hi @asyagelski,
Thanks for submitting the issue. Where do I get to such a publish window?
I looked into a class library, WPF, and ASP.NET Core project but couldn't find the window you showed in your screenshots.

**Comment by asyagelski** [comment]
You can reach the Publish option through right-clicking the project in Solution Explorer or underneath ``Build`` in the toolbar. [Here's a link](https://docs.microsoft.com/en-us/visualstudio/deployment/quickstart-deploy-using-clickonce-folder?view=vs-2019) to an MSDN article on how to do it.

**Comment by fl3pp** [comment]
It seems to work now:

![image](https://user-images.githubusercontent.com/20628550/143865624-6d06865e-363f-4321-bf4c-1539dde46aa5.png)

Please update to the latest version and respond here if the issue isn't resolved for you.
