### ISSUE TITLE
VS2022

### ISSUE THREAD

**Issue by Alex-fbr** [jflepp/JFlepp.VS.Theme.DarkYellow#8]
When are you planning to release this theme for a new VS2022?

**Comment by fl3pp** [comment]
I'm not yet sure there will be a version for VS22 at all. I made this theme using the [Color Theme Designer](https://marketplace.visualstudio.com/items?itemName=ms-madsk.ColorThemeDesigner) provided by MS and until now, it didn't receive an update for VS22. If there is no update for the Theme Designer before the VS22 release, I will try to build a manual version in a reasonable amount of time. If it doesn't work out I guess there will be no VS22 update for this theme.

If you have experience with building themes for VS manually or would like to take on this, I'll be glad to review and accept PRs.

**Comment by imPatSpence** [comment]
I believe there was an update to Color Theme Designer for VS22.  Are there any plans to revisit this?

**Comment by fl3pp** [comment]
Oh yeah, you are right: [Visual Studio Color Theme Designer 2022](https://marketplace.visualstudio.com/items?itemName=idex.colorthemedesigner2022).

Currently, I don't have much spare time, but I guess I will look into it during the next few weeks.

**Comment by fl3pp** [comment]
Hi @Alex-fbr, @imPatSpence,

I've migrated the settings to a new VS22 compatible version and made a pre-release here on GitHub: [1.8 Pre-Release](https://github.com/jflepp/JFlepp.VS.Theme.DarkYellow/releases/tag/1.8).

Could you test the extension and give me feedback? It is difficult for me to check that everything is running smoothly since my local VS installation might be different than the one from others.

Thanks!

**Comment by michaelm7456** [comment]
Hi @jflepp,

I've installed the [1.8 Pre-Release](https://github.com/jflepp/JFlepp.VS.Theme.DarkYellow/releases/tag/1.8) on my local instance of Visual Studio 2022 Community edition and it's working great!

Thank you very much for the rapid VS2022 update and excellent extension!

Looking forward to using VS2022 with this theme still available.

**Comment by fl3pp** [comment]
Updated to version 2.0 on [VS Marketplace](https://marketplace.visualstudio.com/items?itemName=J-Flepp.JFleppVsThemeDarkYellow) with support for VS2022.

@imPatSpence, thanks for pointing out that there was an update for the theme editor available 😊
